config/routes.rb
SlobaIsHere::Application.routes.draw do
  
  get "pages/home"

  get "pages/about"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<div class='container'>
  <div class='column span-6'>
  </div>
  <div id="Banner" class='column span-4'>
  	<img src="..//public/images/logo.jpg" alt="logo">
  </div>
  <div class='column last span-14'>
  </div>
</div>
<div class='container'>
  <div class='column span-6'>
  </div>
  <div id="Sidebar" class='column span-4'>
  	<p>
  		by Slobodan Stanisic
  	</p>
  	<ul>
  		<li><%= link_to "home", home_path %></li>
  		<li>blog</li>
  		<li>about me</li>	
	</ul>
  </div>
  <div class='column span-1'>
  </div>
  <div class='column last span-13'>
  	<img src="..//public/images/portrait.jpg" alt="portrait" />
  </div>
</div>
<div class='container'>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlobaIsHere</title>
  <%= javascript_include_tag :defaults %>
  
  <%= csrf_meta_tag %>
  <!-- [if lt IE 9]>
  	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif] -->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <!-- [if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif] -->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class='container'>
  <div class='column span-6'>
  </div>
  <div id="Banner" class='column span-4'>
  	<img src="..//public/images/logo.jpg" alt="logo">
  </div>
  <div class='column last span-14'>
  </div>
</div>
<div class='container'>
  <div class='column span-6'>
  </div>
  <div id="Sidebar" class='column span-4'>
  	<p>
  		by Slobodan Stanisic
  	</p>
  	<ul>
  		<li><%= link_to "home", home_path %></li>
  		<li>blog</li>
  		<li>about me</li>	
	</ul>
  </div>
  <div class='column span-1'>
  </div>
  <div class='column last span-13'>
  	<img src="..//public/images/portrait.jpg" alt="portrait" />
  </div>
</div>
<div class='container'>
</div> 